export class Config {
  constructor() {
    this.categories = {
      animals: [
        "LION",
        "TIGER",
        "ELEPHANT",
        "GIRAFFE",
        "ZEBRA",
        "PENGUIN",
        "KANGAROO",
        "DOLPHIN",
        "PANDA",
        "KOALA",
        "CHEETAH",
        "GORILLA",
        "BEAR",
        "WOLF",
        "FOX",
        "EAGLE",
        "OWL",
        "SNAKE",
        "CROCODILE",
        "RHINOCEROS",
        "CHAMELEON",
        "HEDGEHOG",
        "PORCUPINE",
        "STINGRAY",
        "ARMADILLO",
        "JELLYFISH",
        "ANTEATER",
        "CAPYBARA",
        "SALAMANDER",
        "WOLVERINE",
        "ALLIGATOR",
        "ANTELOPE",
        "BADGER",
        "BISON",
        "CAMEL",
        "DEER",
        "DINGO",
        "FALCON",
        "FLAMINGO",
        "GECKO",
        "HAMSTER",
        "HIPPO",
        "HORSE",
        "IGUANA",
        "JACKAL",
        "JAGUAR",
        "LEMUR",
        "LEOPARD",
        "LLAMA",
        "LYNX",
        "MONKEY",
        "MOOSE",
        "OCTOPUS",
        "OTTER",
        "PANTHER",
        "PARROT",
        "PEACOCK",
        "PLATYPUS",
        "RABBIT",
        "RACCOON",
        "SEAL",
        "SHARK",
        "SLOTH",
        "SQUIRREL",
        "TOUCAN",
        "TURTLE",
        "WALRUS",
        "WEASEL",
        "WHALE",
        "YAK",
        "ALPACA",
        "BABOON",
        "BUFFALO",
        "CHIPMUNK",
        "COYOTE",
        "GAZELLE",
        "HYENA",
        "IMPALA",
        "MEERKAT",
        "NARWHAL",
        "OCELOT",
        "PIRANHA",
        "QUOKKA",
        "TAPIR",
        "VULTURE",
        "FERRET",
        "MANATEE",
        "OPOSSUM",
        "SKUNK",
        "WOMBAT",
      ],
      countries: [
        "FRANCE",
        "JAPAN",
        "BRAZIL",
        "CANADA",
        "SAMOA",
        "INDIA",
        "CHINA",
        "SPAIN",
        "ITALY",
        "AUSTRALIA",
        "MEXICO",
        "GREECE",
        "THAILAND",
        "PERU",
        "KOREA",
        "TURKEY",
        "AOTEAROA",
        "PHILIPPINES",
        "AFGHANISTAN",
        "LUXEMBOURG",
        "MAURITIUS",
        "MADAGASCAR",
        "NETHERLANDS",
        "NICARAGUA",
        "BANGLADESH",
        "KAZAKHSTAN",
        "LITHUANIA",
        "MACEDONIA",
        "SINGAPORE",
        "SWITZERLAND",
        "SWEDEN",
        "IRELAND",
        "BELGIUM",
        "MALAYSIA",
        "MALDIVES",
        "MALI",
        "MALTA",
        "NIGERIA",
        "NORWAY",
        "PAKISTAN",
        "PANAMA",
        "PARAGUAY",
        "ETHIOPIA",
        "EGYPT",
        "ERITREA",
        "YEMEN",
        "ARGENTINA",
        "AUSTRIA",
        "BOLIVIA",
        "BOTSWANA",
        "BULGARIA",
        "CAMBODIA",
        "CAMEROON",
        "CHILE",
        "COLOMBIA",
        "CONGO",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "DENMARK",
        "ECUADOR",
        "ESTONIA",
        "FIJI",
        "FINLAND",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GUATEMALA",
        "HAITI",
        "HONDURAS",
        "HUNGARY",
        "ICELAND",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "JAMAICA",
        "JORDAN",
        "KENYA",
        "KUWAIT",
        "LAOS",
        "LATVIA",
        "LEBANON",
        "LIBYA",
        "MOROCCO",
        "MYANMAR",
        "NEPAL",
        "POLAND",
        "PORTUGAL",
        "QATAR",
        "ROMANIA",
        "RUSSIA",
        "SENEGAL",
        "SERBIA",
        "SLOVAKIA",
        "SLOVENIA",
        "SOMALIA",
        "SUDAN",
        "SYRIA",
        "TAIWAN",
        "TANZANIA",
        "TUNISIA",
        "UGANDA",
        "UKRAINE",
        "URUGUAY",
        "VENEZUELA",
        "VIETNAM",
        "ZAMBIA",
        "ZIMBABWE",
      ],
      fruits: [
        "APPLE",
        "BANANA",
        "ORANGE",
        "GRAPES",
        "MANGO",
        "KIWIFRUIT",
        "LEMON",
        "PEACH",
        "PEAR",
        "PLUM",
        "CHERRY",
        "COCONUT",
        "PAPAYA",
        "MELON",
        "FIG",
        "LIME",
        "GUAVA",
        "CALAMANSI",
        "BERRY",
        "WATERMELON",
        "CANTALOUPE",
        "STRAWBERRY",
        "BLACKBERRY",
        "GRAPEFRUIT",
        "TANGERINE",
        "CLEMENTINE",
        "POMEGRANATE",
        "BREADFRUIT",
        "CHERIMOYA",
        "PERSIMMON",
        "ELDERBERRY",
        "GOOSEBERRY",
        "BOYSENBERRY",
        "LOGANBERRY",
        "CLOUDBERRY",
        "HUCKLEBERRY",
        "NECTARINE",
        "APRICOT",
        "AVOCADO",
        "PINEAPPLE",
        "HONEYDEW",
        "BLUEBERRY",
        "RASPBERRY",
        "CRANBERRY",
        "TANGERINE",
        "MANDARIN",
        "KIWI",
        "PASSION",
        "DRAGON",
        "STAR",
        "LYCHEE",
        "RAMBUTAN",
        "DURIAN",
        "JACKFRUIT",
        "CUSTARD",
        "SOURSOP",
        "ATEMOYA",
        "QUINCE",
        "CURRANT",
        "MULBERRY",
        "ACAI",
        "GOJI",
        "PLANTAIN",
        "TAMARIND",
        "POMELO",
        "CITRON",
        "YUZU",
        "KUMQUAT",
        "BERGAMOT",
        "UGLI",
        "TANGELO",
        "MINNEOLA",
        "BLOOD",
        "NAVEL",
        "VALENCIA",
        "CARA",
        "JAFFA",
        "SEVILLE",
        "BUDDHA",
        "FINGER",
        "HORNED",
        "AFRICAN",
        "SNAKE",
        "MIRACLE",
        "SUGAR",
        "ICE",
        "MOON",
        "SUN",
        "GOLDEN",
        "HONEY",
        "ROCK",
        "SAND",
        "SNOW",
        "WHITE",
        "BLACK",
        "RED",
        "YELLOW",
        "GREEN",
        "PURPLE",
        "PINK",
        "BLUE",
      ],
      sports: [
        "SOCCER",
        "TENNIS",
        "EQUESTRIAN",
        "SNOWBOARDING",
        "KITESURFING",
        "TRIATHLON",
        "GYMNASTICS",
        "WINDSURFING",
        "PARAGLIDING",
        "ROCKCLIMBING",
        "ICESKATING",
        "CHEERLEADING",
        "STEEPLECHASE",
        "HEPTATHLON",
        "PENTATHLON",
        "CROSSCOUNTRY",
        "RUGBY",
        "BOBSLEIGH",
        "HOCKEY",
        "BOXING",
        "CYCLING",
        "RUNNING",
        "SWIMMING",
        "DIVING",
        "ROWING",
        "JUDO",
        "KARATE",
        "ARCHERY",
        "FENCING",
        "POLO",
        "BASEBALL",
        "BASKETBALL",
        "VOLLEYBALL",
        "FOOTBALL",
        "GOLF",
        "WRESTLING",
        "MARATHON",
        "SAILING",
        "SURFING",
        "SKIING",
        "CLIMBING",
        "HIKING",
        "FISHING",
        "HUNTING",
        "BADMINTON",
        "SQUASH",
        "HANDBALL",
        "WATERPOLO",
        "LACROSSE",
        "CRICKET",
        "DARTS",
        "BILLIARDS",
        "BOWLING",
        "CURLING",
        "SLEDDING",
        "SKYDIVING",
        "BUNGEE",
        "RAFTING",
        "KAYAKING",
        "CANOEING",
        "MOTOCROSS",
        "RACING",
        "KARTING",
        "TAEKWONDO",
        "AIKIDO",
        "CROSSFIT",
        "YOGA",
        "PILATES",
        "AEROBICS",
        "ZUMBA",
        "SPINNING",
        "DANCING",
        "BALLET",
        "ULTIMATE",
        "DISCUS",
        "JAVELIN",
        "SHOTPUT",
        "HAMMER",
        "HURDLES",
        "DECATHLON",
        "BIATHLON",
        "LUGE",
        "SKELETON",
        "MOGULS",
        "FREESTYLE",
        "SLALOM",
        "SNOWSHOE",
        "TELEMARK",
      ],
      colours: [
        "RED",
        "BLUE",
        "GREEN",
        "YELLOW",
        "PURPLE",
        "ORANGE",
        "PINK",
        "BROWN",
        "BLACK",
        "WHITE",
        "GRAY",
        "GOLD",
        "SILVER",
        "VIOLET",
        "INDIGO",
        "MAROON",
        "CORAL",
        "BEIGE",
        "TEAL",
        "NAVY",
        "CRIMSON",
        "SCARLET",
        "RUBY",
        "ROSE",
        "CHERRY",
        "SALMON",
        "PEACH",
        "AMBER",
        "HONEY",
        "MUSTARD",
        "LEMON",
        "LIME",
        "MINT",
        "SAGE",
        "OLIVE",
        "FOREST",
        "EMERALD",
        "JADE",
        "TURQUOISE",
        "CYAN",
        "AZURE",
        "COBALT",
        "ROYAL",
        "PERIWINKLE",
        "CHARTREUSE",
        "CHAMPAGNE",
        "LAVENDER",
        "LILAC",
        "PLUM",
        "MAGENTA",
        "FUCHSIA",
        "BURGUNDY",
        "WINE",
        "RUST",
        "COPPER",
        "BRONZE",
        "TAN",
        "KHAKI",
        "SAND",
        "CREAM",
        "IVORY",
        "PEARL",
        "PLATINUM",
        "STEEL",
        "CHARCOAL",
        "ONYX",
        "JET",
        "EBONY",
        "MAHOGANY",
        "CHESTNUT",
        "COFFEE",
        "CHOCOLATE",
        "COCOA",
        "CARAMEL",
        "VANILLA",
        "BISQUE",
        "SNOW",
        "FROST",
        "BONE",
        "LINEN",
        "WHEAT",
        "BUFF",
        "FAWN",
        "TAUPE",
        "MAUVE",
        "BLUSH",
        "ROUGE",
        "CERISE",
        "GARNET",
        "CARDINAL",
        "BRICK",
        "FLAME",
        "TANGERINE",
        "APRICOT",
        "PAPAYA",
        "CANARY",
        "BANANA",
        "BUTTER",
        "CREAM",
        "CITRINE",
        "SPRING",
        "SEAFOAM",
        "AQUA",
        "POWDER",
        "SKY",
        "CERULEAN",
        "SAPPHIRE",
        "MIDNIGHT",
        "SLATE",
        "STEEL",
        "STORM",
        "PEWTER",
        "ASH",
        "SMOKE",
        "MIST",
        "FOG",
      ],
      food: [
        "PIZZA",
        "PASTA",
        "SUSHI",
        "BURGER",
        "PANCIT",
        "SALAD",
        "CURRY",
        "BREAD",
        "TAPSILOG",
        "SOUP",
        "RICE",
        "CAKE",
        "CHIPS",
        "FISH",
        "WRAP",
        "ADOBO",
        "SINIGANG",
        "HALOHALO",
        "QUESADILLA",
        "ENCHILADA",
        "SPRINGROLL",
        "SAUERKRAUT",
        "AMPALAYA",
        "TACOS",
        "BURRITO",
        "NACHOS",
        "RAMEN",
        "TEMPURA",
        "MISO",
        "TOFU",
        "KIMCHI",
        "BIBIMBAP",
        "BULGOGI",
        "POUTINE",
        "MAPLE",
        "BAGEL",
        "PRETZEL",
        "SANDWICH",
        "EGGS",
        "CHEESE",
        "YOGURT",
        "BUTTER",
        "HONEY",
        "CHOCOLATE",
        "COOKIES",
        "DONUTS",
        "MUFFIN",
        "PANCAKES",
        "WAFFLES",
        "CEREAL",
        "OATMEAL",
        "GRANOLA",
        "SMOOTHIE",
        "LASAGNA",
        "RAVIOLI",
        "GNOCCHI",
        "RISOTTO",
        "PAELLA",
        "GAZPACHO",
        "TORTILLA",
        "EMPANADA",
        "CHURROS",
        "FALAFEL",
        "HUMMUS",
        "KEBAB",
        "SHAWARMA",
        "COUSCOUS",
        "TAJINE",
        "CROISSANT",
        "BAGUETTE",
        "CREPE",
        "QUICHE",
        "FONDUE",
        "PIEROGI",
        "BORSCHT",
        "CAVIAR",
        "VODKA",
        "GYOZA",
        "YAKITORI",
        "TERIYAKI",
        "WASABI",
        "EDAMAME",
        "DUMPLINGS",
        "NOODLES",
        "WONTONS",
        "SATAY",
        "LAKSA",
        "RENDANG",
        "SAMOSA",
        "BIRYANI",
        "MASALA",
        "NAAN",
        "CHAPATI",
        "TIKKA",
      ],
    };

    this.difficulties = {
      easy: {
        size: 8,
        wordCount: 6,
        timeLimit: 300,
      },
      medium: {
        size: 10,
        wordCount: 8,
        timeLimit: 240,
      },
      hard: {
        size: 12,
        wordCount: 10,
        timeLimit: 180,
      },
    };

    this.settings = {
      difficulty: "easy",
      theme: "dark",
      sound: true,
      timeLimit: true,
    };

    this.credits = {
      version: "1.0.1",
      developer: "Manu and the Little Chef",
      year: "2025",
      technologies: ["HTML5", "JavaScript", "Tailwind CSS", "Apache Cordova"],
      description: "A fun word search game for Camille on her 32nd birthday!",
      repository: "https://github.com/manu72/word-search-game",
    };

    this.birthday = {
      date: "2025-07-05",
      name: "Camille",
      specialMessageFrequency: {
        min: 3,
        max: 9,
      },
    };

    this.loadFromStorage();
  }

  loadFromStorage() {
    const savedSettings = localStorage.getItem("wordSearchSettings");
    if (savedSettings) {
      this.settings = { ...this.settings, ...JSON.parse(savedSettings) };
    }
  }

  saveToStorage() {
    localStorage.setItem("wordSearchSettings", JSON.stringify(this.settings));
  }

  getTheme() {
    return this.settings.theme;
  }

  getDifficulty() {
    return this.difficulties[this.settings.difficulty];
  }

  getCompletionData() {
    const saved = localStorage.getItem("wordSearchCompletions");
    if (saved) {
      return JSON.parse(saved);
    }
    return {
      count: 0,
      nextSpecialMessage: this.getRandomSpecialMessageTrigger(),
    };
  }

  saveCompletionData(data) {
    localStorage.setItem("wordSearchCompletions", JSON.stringify(data));
  }

  getRandomSpecialMessageTrigger() {
    const { min, max } = this.birthday.specialMessageFrequency;
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  getDaysUntilBirthday() {
    const today = new Date();
    const birthdayParts = this.birthday.date.split("-");
    const birthdayYear = parseInt(birthdayParts[0]);
    const birthdayMonth = parseInt(birthdayParts[1]) - 1; // Month is 0-indexed
    const birthdayDay = parseInt(birthdayParts[2]);

    let birthdayThisYear = new Date(
      today.getFullYear(),
      birthdayMonth,
      birthdayDay
    );

    // If birthday has already passed this year, calculate for next year
    if (birthdayThisYear < today) {
      birthdayThisYear = new Date(
        today.getFullYear() + 1,
        birthdayMonth,
        birthdayDay
      );
    }

    const timeDiff = birthdayThisYear.getTime() - today.getTime();
    return Math.ceil(timeDiff / (1000 * 3600 * 24));
  }

  getWinMessage() {
    const completionData = this.getCompletionData();
    completionData.count++;

    let message = "🎉 Congratulations! You found all the words!";
    let isSpecialMessage = false;

    if (completionData.count >= completionData.nextSpecialMessage) {
      const daysUntil = this.getDaysUntilBirthday();
      message = `🎉 Congratulations! You found all the words! Did you know that it is only ${daysUntil} days until ${this.birthday.name}'s birthday?`;
      completionData.nextSpecialMessage =
        completionData.count + this.getRandomSpecialMessageTrigger();
      isSpecialMessage = true;
    }

    this.saveCompletionData(completionData);
    return { message, isSpecialMessage };
  }
}
